# Generated by Django 4.2.9 on 2024-02-01 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("amount", models.FloatField()),
                ("paid_by", models.JSONField()),
                ("shared_by", models.JSONField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("added_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="splitEase.user")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="splitEase.group")),
            ],
            options={
                "db_table": "transactions",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="splitEase.group")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="splitEase.user")),
            ],
            options={
                "db_table": "memberships",
                "unique_together": {("group", "user")},
            },
        ),
    ]
